package com.lhy.boot.shardingSphere.mapper;

import com.lhy.boot.shardingSphere.model.Member;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    Member selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKey(Member record);
}