package com.lhy.boot.shardingSphere.mapper;

import com.lhy.boot.shardingSphere.model.Order;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    Order selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKey(Order record);
}