package com.lhy.boot.shardingSphere.mapper;

import com.lhy.boot.shardingSphere.model.OrderItem;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    OrderItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 18:11:15 CST 2020
     */
    int updateByPrimaryKey(OrderItem record);
}