package com.lhy.boot.shardingSphere.model;

import java.io.Serializable;
import java.util.Date;

public class OrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item0.item_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item0.product_name
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item0.item_account
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private Double itemAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_item0
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item0.item_id
     *
     * @return the value of t_order_item0.item_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item0.item_id
     *
     * @param itemId the value for t_order_item0.item_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item0.order_id
     *
     * @return the value of t_order_item0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item0.order_id
     *
     * @param orderId the value for t_order_item0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item0.product_name
     *
     * @return the value of t_order_item0.product_name
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item0.product_name
     *
     * @param productName the value for t_order_item0.product_name
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item0.item_account
     *
     * @return the value of t_order_item0.item_account
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public Double getItemAccount() {
        return itemAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item0.item_account
     *
     * @param itemAccount the value for t_order_item0.item_account
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setItemAccount(Double itemAccount) {
        this.itemAccount = itemAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item0.create_time
     *
     * @return the value of t_order_item0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item0.create_time
     *
     * @param createTime the value for t_order_item0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}