package com.lhy.boot.shardingSphere.model;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.member_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.order_code
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.order_amount
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.status
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order0
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.order_id
     *
     * @return the value of t_order0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.order_id
     *
     * @param orderId the value for t_order0.order_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.member_id
     *
     * @return the value of t_order0.member_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.member_id
     *
     * @param memberId the value for t_order0.member_id
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.order_code
     *
     * @return the value of t_order0.order_code
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.order_code
     *
     * @param orderCode the value for t_order0.order_code
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.order_amount
     *
     * @return the value of t_order0.order_amount
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.order_amount
     *
     * @param orderAmount the value for t_order0.order_amount
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount == null ? null : orderAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.status
     *
     * @return the value of t_order0.status
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.status
     *
     * @param status the value for t_order0.status
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order0.create_time
     *
     * @return the value of t_order0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order0.create_time
     *
     * @param createTime the value for t_order0.create_time
     *
     * @mbg.generated Mon Mar 30 23:10:47 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}